In [1]:
import numpy as np
import pandas as pd

In [10]:
#df = pd.read_excel('BaseDW-MilLinhas.xls')
pathExcel = 'BaseDW-MilLinhas.xls'
allExcelNames = pd.ExcelFile(pathExcel).sheet_names

In [13]:
for currentExcelName in allExcelNames:
    df = pd.read_excel(caminho_planilha, sheet_name=currentExcelName)
    print(f'Current Table: {currentExcelName}')
    print(df)

Current Table: DIM_Clientes
   COD_CLIENTE      NOME_CLIENTE SEXO_CLIENTE           BAIRRO       CIDADE  \
0            1   Jose dos Testes            M       MANGABEIRA  JOAO PESSOA
1            2  Maria dos Testes            F            TIROL        NATAL
2            3    Andreia jargão            F  NOVA PARNAMIRIM   PARNAMIRIM
3            4     Viviane Maria            F       CANDELARIA        NATAL
4            5       Pedro Paulo            M           CENTRO        NATAL
5            6     Joao da Silva            M       PETROPOLIS        NATAL
6            7      Juarez Teste            M  NOVA PARNAMIRIM   PARNAMIRIM
7            8       Joana Maria            F       MANGABEIRA  JOAO PESSOA
8            9    Miguel Tavares            M            TIROL        NATAL
9           10     Michele Maria            F       CANDELARIA        NATAL

   UF    PAIS
0  PB  BRASIL
1  RN  BRASIL
2  RN  BRASIL
3  RN  BRASIL
4  RN  BRASIL
5  RN  BRASIL
6  RN  BRASIL
7  PB  BRASIL
8  RN  BRASIL
9  RN  BRASIL
Current Table: DIM_Produtos
   COD_PRODUTO        DESCRICAO      TIPO_PRODUTO FABRICANTE
0            1       Chocoloate          Alimento     Nestle
1            2        Televisão  EletroEletrônico    Samsung
2            3          Celular  EletroEletrônico    Samsung
3            4         Camiseta         Vestuario    Colombo
4            5       Mp3 Player  EletroEletrônico       Sony
5            6            Tênis           Calçado  Olimpikus
6            7            Calça         Vestuario      Levis
7            8     Refrigerante          Alimento  Coca-Cola
8            9            Arroz          Alimento   Tio Joao
9           10  Aparelho de Som  EletroEletrônico    Philips
Current Table: DIM_Vendedores
   COD_VENDEDOR       NOME_VENDEDOR  SALARIO    INSS    IRPF  SAL LIQUIDO
0             1  Antonio das Vendas     1234   98.72   92.55      1042.73
1             2    Kassia Vendedora     2380  190.40  178.50      2011.10
2             3         Maria Silva     5600  448.00  420.00      4732.00
3             4          José Paulo     1400  112.00  105.00      1183.00
4             5       João Medeiros      520   41.60   39.00       439.40
5             6      Timoteo Brasil     1200   96.00   90.00      1014.00
6             7     Ricardo Roberto      900   72.00   67.50       760.50
7             8        Tiago Vieira     1080   86.40   81.00       912.60
8             9   Pedro Luiz Barros     4000  320.00  300.00      3380.00
9            10     Thiago Vinicius     1128   90.24   84.60       953.16
Current Table: DIM_Tempo
    COD_MES           DESC_MES   ANO  DIA_DA_SEMANA
0     12007    Janeiro de 2007  1990        DOMINGO
1     22007  Fevereiro de 2007  1991  SEGUNDA-FEIRA
2     32007      Março de 2007  1992    TERÇA-FEIRA
3     42007      Abril de 2007  1993   QUARTA-FEIRA
4     52007       Maio de 2007  1994   QUINTA-FEIRA
5     62007      Junho de 2007  1995    SEXTA-FEIRA
6     72007      Julho de 2007  1996         SÁBADO
7     82007     Agosto de 2007  1997            NaN
8     92007   Setembro de 2007  1998            NaN
9    102007    Outubro de 2007  1999            NaN
10   112007   Novembro de 2007  2000            NaN
11   122007   Dezembro de 2007  2001            NaN
12   122008   Dezembro de 2008  2002            NaN
13   122009   Dezembro de 2009  2003            NaN
14   122010   Dezembro de 2010  2004            NaN
15   122011   Dezembro de 2011  2005            NaN
16   122012   Dezembro de 2012  2006            NaN
17   122013   Dezembro de 2013  2007            NaN
18   122014   Dezembro de 2014  2008            NaN
19   122015   Dezembro de 2015  2009            NaN
20   122016   Dezembro de 2016  2010            NaN
21   122017   Dezembro de 2017  2011            NaN
22   122018   Dezembro de 2018  2012            NaN
23   122019   Dezembro de 2019  2013            NaN
24   122020   Dezembro de 2020  2014            NaN
25   122021   Dezembro de 2021  2015            NaN
26   122022   Dezembro de 2022  2016            NaN
27   122023   Dezembro de 2023  2017            NaN
28   122024   Dezembro de 2024  2018            NaN
29   122025   Dezembro de 2025  2019            NaN
30   122026   Dezembro de 2026  2020            NaN
31   122027   Dezembro de 2027  2021            NaN
32   122028   Dezembro de 2028  2022            NaN
33   122029   Dezembro de 2029  2023            NaN
34   122030   Dezembro de 2030  2024            NaN
35   122031   Dezembro de 2031  2025            NaN
36   122032   Dezembro de 2032  2026            NaN
37   122033   Dezembro de 2033  2027            NaN
38   122034   Dezembro de 2034  2028            NaN
39   122035   Dezembro de 2035  2029            NaN
40   122036   Dezembro de 2036  2030            NaN
41   122037   Dezembro de 2037  2031            NaN
Current Table: FATO_Vendas
      COD_CLIENTE  COD_PRODUTO  COD_VENDEDOR  COD_MES  QTDE_VENDIDA  \
0               1            1             1    12007             1
1               2            2             2    22007             2
2               3            3             3    32007             3
3               4            4             4    42007             4
4               5            5             5    52007             5
...           ...          ...           ...      ...           ...
1015            1            3             1   122007             3
1016            1            3             1   122007             3
1017            1            3             1   122007             4
1018            1            3             1   122007             4
1019            1            3             2   122007             4

      VALOR_VENDA  VALOR_IMPOSTO
0              10            1.0
1               1            0.1
2               3            0.3
3               4            0.4
4               5            0.5
...           ...            ...
1015           78            7.8
1016            5            0.5
1017            5            0.5
1018            5            0.5
1019            5            0.5

[1020 rows x 7 columns]